### ISSUE TITLE
Tests fail some arches

### ISSUE THREAD

**Issue by yaneti** [chergert/jsonrpc-glib#2]
Tests fail on eg: armv7hl
....
Executing(%check): /bin/sh -e /var/tmp/rpm-tmp.aNOQ3z
+ umask 022
+ cd /builddir/build/BUILD
+ cd jsonrpc-glib-3.26.0
+ /usr/bin/ninja test -v -j4 -C armv7hl-redhat-linux-gnueabi
ninja: Entering directory `armv7hl-redhat-linux-gnueabi'
[0/1] /usr/bin/python3 -u /usr/bin/meson test --no-rebuild --print-errorlogs
1/3 test-message                            FAIL     0.10 s
2/3 test-server                             OK       0.04 s
3/3 test-stress                             OK       1.26 s
OK:         2
FAIL:       1
SKIP:       0
TIMEOUT:    0
The output from the failed tests:
1/3 test-message                            FAIL     0.10 s
--- command ---
G_TEST_SRCDIR='/builddir/build/BUILD/jsonrpc-glib-3.26.0/tests' G_TEST_BUILDDIR='/builddir/build/BUILD/jsonrpc-glib-3.26.0/armv7hl-redhat-linux-gnueabi/tests' G_DEBUG='gc-friendly' GSETTINGS_BACKEND='memory' PYTHONDONTWRITEBYTECODE='yes' MALLOC_CHECK_='2' /builddir/build/BUILD/jsonrpc-glib-3.26.0/armv7hl-redhat-linux-gnueabi/tests/test-message
--- stdout ---
/Jcon/basic: 
--- stderr ---
(/builddir/build/BUILD/jsonrpc-glib-3.26.0/armv7hl-redhat-linux-gnueabi/tests/test-message:7485): jsonrpc-message-CRITICAL **: file ../src/jsonrpc-message.c: line 190 (jsonrpc_message_build_array): should not be reached
-------
Full log written to /builddir/build/BUILD/jsonrpc-glib-3.26.0/armv7hl-redhat-linux-gnueabi/meson-logs/testlog.txt
FAILED: meson-test 
/usr/bin/python3 -u /usr/bin/meson test --no-rebuild --print-errorlogs
ninja: build stopped: subcommand failed.
....

**Comment by yaneti** [comment]
Specifically test-message fails on all but x86_64 and s390x
https://koji.fedoraproject.org/koji/taskinfo?taskID=21811336

**Comment by yaneti** [comment]
Local test on armv7hl

<pre>(gdb) r
Starting program: /home/yaneti/jsonrpc-glib/build/tests/test-message 
Missing separate debuginfos, use: dnf debuginfo-install glibc-2.26.90-15.fc28.armv7hl
Cannot parse expression `.L1170 4@r4'.
warning: Probes-based dynamic linker interface failed.
Reverting to original interface.

[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/libthread_db.so.1".
/Jcon/basic: 
(/home/yaneti/jsonrpc-glib/build/tests/test-message:6228): jsonrpc-message-CRITICAL **: file ../src/jsonrpc-message.c: line 190 (jsonrpc_message_build_array): should not be reached

Program received signal SIGTRAP, Trace/breakpoint trap.
0xb6cfb1f0 in raise () from /lib/libc.so.6
Missing separate debuginfos, use: dnf debuginfo-install glib2-2.53.7-1.fc28.armv7hl json-glib-1.3.2-3.fc27.armv7hl libblkid-2.30.1-5.fc27.armv7hl libffi-3.1-14.fc27.armv7hl libgcc-7.2.1-1.fc28.armv7hl libmount-2.30.1-5.fc27.armv7hl libselinux-2.7-3.fc28.armv7hl libuuid-2.30.1-5.fc27.armv7hl pcre-8.41-1.fc27.2.armv7hl pcre2-10.30-1.fc27.armv7hl zlib-1.2.11-4.fc27.armv7hl
(gdb) bt full
#0  0xb6cfb1f0 in raise () at /lib/libc.so.6
#1  0xb6e96da8 in g_logv () at /lib/libglib-2.0.so.0
#2  0xb6e96f1c in g_log () at /lib/libglib-2.0.so.0
#3  0xb6fb758c in jsonrpc_message_build_array (builder=0xbefff01c, param=0x137d8, args=...) at ../src/jsonrpc-message.c:190
        valptr = 0x137d8
        __func__ = "jsonrpc_message_build_array"
#4  0xb6fb7730 in jsonrpc_message_build_array (builder=0xbefff01c, param=0x137d8, args=...) at ../src/jsonrpc-message.c:212
        valptr = 0xbefff140
        __func__ = "jsonrpc_message_build_array"
#5  0xb6fb7730 in jsonrpc_message_build_array (builder=0xbefff01c, param=0xbefff140, args=...) at ../src/jsonrpc-message.c:212
        valptr = 0x137e4
        __func__ = "jsonrpc_message_build_array"
#6  0xb6fb7170 in jsonrpc_message_build_object (builder=0xbefff01c, param=0x137e4, args=...) at ../src/jsonrpc-message.c:120
        keyptr = 0x137e0
        valptr = 0x137e8
        key = 0x137e0 "baz"
        __func__ = "jsonrpc_message_build_object"
#7  0xb6fb7120 in jsonrpc_message_build_object (builder=0xbefff01c, param=0x137e0, args=...) at ../src/jsonrpc-message.c:113
        keyptr = 0x137e0
        valptr = 0x137e4
        key = 0x137e0 "baz"
        __func__ = "jsonrpc_message_build_object"
#8  0xb6fb735c in jsonrpc_message_build_object (builder=0xbefff01c, param=0x137e0, args=...) at ../src/jsonrpc-message.c:152
        keyptr = 0x137c8
        valptr = 0x137c0
        key = 0x137c8 "bar"
        __func__ = "jsonrpc_message_build_object"
#9  0xb6fb735c in jsonrpc_message_build_object (builder=0xbefff01c, param=0x137c8, args=...) at ../src/jsonrpc-message.c:152
        keyptr = 0x137d4
        valptr = 0x137cc
        key = 0x137d4 "foo"
        __func__ = "jsonrpc_message_build_object"
#10 0xb6fb77fc in jsonrpc_message_new_valist (first_param=0x137d4, args=...) at ../src/jsonrpc-message.c:226
        builder = 
              {u = {s = {partial_magic = 195584, type = 0x31260, y = {0, 0, 1, 1, 201360, 1, 0, 3, 1033660112, 0, 0, 0, 0, 0}}, x = {195584, 201312, 0, 0, 1, 1, 201360, 1, 0, 3, 1033660112, 0, 0, 0, 0, 0}}}
#11 0xb6fb78c0 in jsonrpc_message_new (first_param=0x137d4) at ../src/jsonrpc-message.c:241
        ret = 0x2e500
        args = {__ap = 0xbefff09c}
        __func__ = "jsonrpc_message_new"
#12 0x00010e58 in test_basic () at ../tests/test-message.c:16
        node = 0x0
        parser = 0x0
        error = 0x0
        deserialized = 0x0
        foo1 = 0x0
        baz_baz_baz = 0
        r = -1090522832
        __func__ = "test_basic"
#13 0xb6eb88d0 in g_test_run_suite_internal () at /lib/libglib-2.0.so.0
#14 0xb6eb87f8 in g_test_run_suite_internal () at /lib/libglib-2.0.so.0
#15 0xb6eb8b2c in g_test_run_suite () at /lib/libglib-2.0.so.0
#16 0xb6eb8b60 in g_test_run () at /lib/libglib-2.0.so.0
#17 0x00013340 in main (argc=1, argv=0xbefff3e4) at ../tests/test-message.c:178</pre>

**Comment by yaneti** [comment]
With the latest fixes test-message succeeds all all Fedora arches.
Again with the latest fixes test-stress seems to fail sporadically so I'll open a different issue for that.
